// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuoyastudqphomimqagu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51b3lhc3R1ZHFwaG9taW1xYWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNTk3ODQsImV4cCI6MjA1MzYzNTc4NH0.u4bOlOOwCKOdF6qKqd8XDxcUqmUhCXTdJ07IOF5s35U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);